import numpy as np
arr=np.random .rand(5)
print(arr)
arr1=np.empty((4,2))
print(arr1)
arr2=np.zeros((3,2))
print(arr2)
arr3=np.ones((4,3,2))
print(arr3)
print("question no 3")
arr4=np.arange(2,11).reshape(3,3)
print(arr4)
print("question no 4")
arr5=np.empty(10)
arr5[6]=11
print(arr5)
print("question no 5")
arr6=np.array([1,2,3,4,5,6])
print(arr6[::-1])
print("question 6")
float_convert=arr6.astype(float)
print(float_convert)
